"""Initial schema

Revision ID: 543e99e85a6a
Revises: 
Create Date: 2026-09-15 20:29:45.538661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.types


# revision identifiers, used by Alembic.
revision: str = '543e99e85a6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('species',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_uk', sa.String(length=100), nullable=False),
    sa.Column('is_food_producing', sa.Boolean(), nullable=False),
    sa.Column('typical_min_weight_kg', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('typical_max_weight_kg', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_code'), 'species', ['code'], unique=True)
    op.create_table('substance',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('name_uk', sa.String(length=150), nullable=False),
    sa.Column('pharmacological_group', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contraindication',
    sa.Column('substance_id', app.models.types.GUID(), nullable=False),
    sa.Column('species_id', app.models.types.GUID(), nullable=True),
    sa.Column('condition', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('absolute', 'caution', name='severity', native_enum=False), nullable=False),
    sa.Column('message_uk', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['substance_id'], ['substance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dose_rule',
    sa.Column('substance_id', app.models.types.GUID(), nullable=False),
    sa.Column('species_id', app.models.types.GUID(), nullable=False),
    sa.Column('route', sa.Enum('iv', 'im', 'sc', 'po', 'topical', 'other', name='route', native_enum=False), nullable=False),
    sa.Column('indication', sa.String(length=255), nullable=True),
    sa.Column('dose_min', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('dose_max', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('dose_unit', sa.Enum('mg_per_kg', 'mcg_per_kg', 'iu_per_kg', 'ml_per_kg', 'ml_per_10kg', 'mg_per_animal', 'ml_per_animal', name='doseunit', native_enum=False), nullable=False),
    sa.Column('max_total_dose', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_total_dose_unit', sa.Enum('mg', 'mcg', 'iu', 'ml', name='maxtotaldoseunit', native_enum=False), nullable=True),
    sa.Column('frequency', sa.String(length=150), nullable=True),
    sa.Column('duration', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['substance_id'], ['substance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('trade_name', sa.String(length=150), nullable=False),
    sa.Column('manufacturer', sa.String(length=150), nullable=True),
    sa.Column('substance_id', app.models.types.GUID(), nullable=False),
    sa.Column('form', sa.Enum('injection_solution', 'oral_solution', 'tablet', 'powder', 'suspension', 'other', name='productform', native_enum=False), nullable=False),
    sa.Column('concentration_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('concentration_unit', sa.Enum('mg_per_ml', 'mcg_per_ml', 'iu_per_ml', 'mg_per_tablet', 'mg_per_g', name='concentrationunit', native_enum=False), nullable=False),
    sa.Column('tablet_divisible_by', sa.SmallInteger(), nullable=True),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['substance_id'], ['substance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdrawal_period',
    sa.Column('product_id', app.models.types.GUID(), nullable=False),
    sa.Column('species_id', app.models.types.GUID(), nullable=False),
    sa.Column('route', sa.Enum('iv', 'im', 'sc', 'po', 'topical', 'other', name='route', native_enum=False), nullable=False),
    sa.Column('food_product', sa.Enum('meat', 'milk', 'eggs', 'honey', name='foodproduct', native_enum=False), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawal_period')
    op.drop_table('product')
    op.drop_table('dose_rule')
    op.drop_table('contraindication')
    op.drop_table('substance')
    op.drop_index(op.f('ix_species_code'), table_name='species')
    op.drop_table('species')
    # ### end Alembic commands ###
